# Name of the workflow, which will appear in the "Actions" tab of your GitHub repo
name: Python Unit Tests

# This section defines when the workflow will run.
# It will run on every push to the 'main' branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# This section defines the jobs to be run.
jobs:
  # We have one job, which we'll call 'build-and-test'
  build-and-test:
    # This job will run on the latest version of Ubuntu Linux
    runs-on: ubuntu-latest

    # These are the individual steps the job will perform
    steps:
      # Step 1: Checks out your repository's code so the workflow can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Sets up the specific version of Python you want to use
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      # Step 3: Installs your project's dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Runs your unit tests using the correct test file name
      - name: Test with unittest
        run: python3 -m unittest test_gemini_project.py
